stages:
  split:
    cmd: agot data split --seed ${split.seed} --test-size ${split.test_size} --filename data/raw/cards.jsonl
    deps:
    - data/raw/cards.jsonl
    outs:
    - data/splits/test.jsonl
    - data/splits/train.jsonl

  lm_preprocess_train:
    cmd: agot data preprocess-kenlm data/splits/train.jsonl ${lm_preprocess.key}
    deps:
    - data/splits/train.jsonl
    outs:
    - data/lm/train.txt

  lm_preprocess_test:
    cmd: agot data preprocess-kenlm data/splits/test.jsonl ${lm_preprocess.key}
    deps:
    - data/splits/test.jsonl
    outs:
    - data/lm/test.txt

  kenlm_train:
    cmd: lmplz -o ${kenlm.order} --text data/lm/train.txt --arpa models/kenlm/lm.arpa
    deps:
    - data/lm/train.txt
    outs:
    - models/kenlm/lm.arpa

  kenlm_evaluate:
    cmd: agot kenlm evaluate
    deps:
    - data/lm/train.txt
    - data/lm/test.txt
    - models/kenlm/lm.arpa
    metrics:
    - metrics/kenlm.json
