stages:
  split:
    cmd: python scripts/split.py --seed ${split.seed} --test-size ${split.test_size} --filename data/raw/cards.jsonl
    deps:
    - data/raw/cards.jsonl
    outs:
    - data/splits/test.jsonl
    - data/splits/train.jsonl

  lm_preprocess_train:
    cmd: python scripts/preprocess_lm.py data/splits/train.jsonl ${lm_preprocess.key}
    deps:
    - data/splits/train.jsonl
    outs:
    - data/lm/train.txt

  lm_preprocess_test:
    cmd: python scripts/preprocess_lm.py data/splits/test.jsonl ${lm_preprocess.key}
    deps:
    - data/splits/test.jsonl
    outs:
    - data/lm/test.txt

  kenlm_train:
    cmd: lmplz -o ${kenlm.order} --text data/lm/train.txt --arpa models/kenlm/lm.arpa
    deps:
    - data/lm/train.txt
    outs:
    - models/kenlm/lm.arpa

  kenlm_evaluate:
    cmd: python scripts/ngram_lm.py
    deps:
    - data/lm/train.txt
    - data/lm/test.txt
    - models/kenlm/lm.arpa
    metrics:
    - metrics/kenlm.json
